package com.weibar.service.mapper;

import com.weibar.pojo.db.WeibarMerchantsHorseRaceLampSettingInfo;
import com.weibar.pojo.db.WeibarMerchantsHorseRaceLampSettingInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeibarMerchantsHorseRaceLampSettingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int countByExample(WeibarMerchantsHorseRaceLampSettingInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int deleteByExample(WeibarMerchantsHorseRaceLampSettingInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int deleteByPrimaryKey(Long merchantid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int insert(WeibarMerchantsHorseRaceLampSettingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int insertSelective(WeibarMerchantsHorseRaceLampSettingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    List<WeibarMerchantsHorseRaceLampSettingInfo> selectByExample(WeibarMerchantsHorseRaceLampSettingInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    WeibarMerchantsHorseRaceLampSettingInfo selectByPrimaryKey(Long merchantid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeibarMerchantsHorseRaceLampSettingInfo record, @Param("example") WeibarMerchantsHorseRaceLampSettingInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int updateByExample(@Param("record") WeibarMerchantsHorseRaceLampSettingInfo record, @Param("example") WeibarMerchantsHorseRaceLampSettingInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int updateByPrimaryKeySelective(WeibarMerchantsHorseRaceLampSettingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_horse_race_lamp_setting_info
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int updateByPrimaryKey(WeibarMerchantsHorseRaceLampSettingInfo record);
}