
### 正式环境
wechat:
  mp:
    appId: wxa105b2133d0dd8b0
    secret: 4c88575249eec6450bb6cb5d296520e4
    token: weibar2017
    aesKey:
  pay:
    appId: wxd62da453fe48632c
    mchKey: nxApb3xKPYrHyRxq7wai4pWUyQOQeLyU
    mchId: 1493754672
  miniapp:
    appid: wxd62da453fe48632c
    secret: f28addb4676847e1ebd54b8e67ca7509
    token:
    aesKey:
    msgDataFormat: JSON


### 正式环境DB
spring:
    datasource:
        name: test
        url: jdbc:mysql://120.79.12.173:3306/weibar?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
        username: weibar
        password: weibar_10086
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


### 测试环境DB
#spring:
#    datasource:
#        name: test
#        url: jdbc:mysql://rm-wz9l3k9adb590oksvo.mysql.rds.aliyuncs.com:3306/weibar?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
#        username: root
#        password: Weibar2017
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20