package com.weibar.service.mapper;

import com.weibar.pojo.db.UserBaseInfo;
import com.weibar.pojo.db.UserBaseInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int countByExample(UserBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int deleteByExample(UserBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int insert(UserBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int insertSelective(UserBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    List<UserBaseInfo> selectByExample(UserBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    UserBaseInfo selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserBaseInfo record, @Param("example") UserBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int updateByExample(@Param("record") UserBaseInfo record, @Param("example") UserBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int updateByPrimaryKeySelective(UserBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base_info
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    int updateByPrimaryKey(UserBaseInfo record);
}