package com.weibar.service.mapper;

import com.weibar.pojo.db.WeibarRedpackageDepositDetail;
import com.weibar.pojo.db.WeibarRedpackageDepositDetailCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeibarRedpackageDepositDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int countByExample(WeibarRedpackageDepositDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int deleteByExample(WeibarRedpackageDepositDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int insert(WeibarRedpackageDepositDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int insertSelective(WeibarRedpackageDepositDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    List<WeibarRedpackageDepositDetail> selectByExample(WeibarRedpackageDepositDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    WeibarRedpackageDepositDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") WeibarRedpackageDepositDetail record, @Param("example") WeibarRedpackageDepositDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int updateByExample(@Param("record") WeibarRedpackageDepositDetail record, @Param("example") WeibarRedpackageDepositDetailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int updateByPrimaryKeySelective(WeibarRedpackageDepositDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_redpackage_deposit_detail
     *
     * @mbggenerated Sun Feb 11 16:12:00 CST 2018
     */
    int updateByPrimaryKey(WeibarRedpackageDepositDetail record);
}