package com.weibar.service.mapper;

import com.weibar.pojo.db.WeibarPrivateChatIdMap;
import com.weibar.pojo.db.WeibarPrivateChatIdMapCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeibarPrivateChatIdMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int countByExample(WeibarPrivateChatIdMapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int deleteByExample(WeibarPrivateChatIdMapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int deleteByPrimaryKey(Long chatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int insert(WeibarPrivateChatIdMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int insertSelective(WeibarPrivateChatIdMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    List<WeibarPrivateChatIdMap> selectByExample(WeibarPrivateChatIdMapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    WeibarPrivateChatIdMap selectByPrimaryKey(Long chatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") WeibarPrivateChatIdMap record, @Param("example") WeibarPrivateChatIdMapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int updateByExample(@Param("record") WeibarPrivateChatIdMap record, @Param("example") WeibarPrivateChatIdMapCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int updateByPrimaryKeySelective(WeibarPrivateChatIdMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_private_chat_id_map
     *
     * @mbggenerated Tue Mar 27 18:15:48 CST 2018
     */
    int updateByPrimaryKey(WeibarPrivateChatIdMap record);
}