package com.weibar.service.mapper;

import com.weibar.pojo.db.WeibarMerchantsBarrageInfo;
import com.weibar.pojo.db.WeibarMerchantsBarrageInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeibarMerchantsBarrageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int countByExample(WeibarMerchantsBarrageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int deleteByExample(WeibarMerchantsBarrageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int insert(WeibarMerchantsBarrageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int insertSelective(WeibarMerchantsBarrageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    List<WeibarMerchantsBarrageInfo> selectByExample(WeibarMerchantsBarrageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    WeibarMerchantsBarrageInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") WeibarMerchantsBarrageInfo record, @Param("example") WeibarMerchantsBarrageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int updateByExample(@Param("record") WeibarMerchantsBarrageInfo record, @Param("example") WeibarMerchantsBarrageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int updateByPrimaryKeySelective(WeibarMerchantsBarrageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_info
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    int updateByPrimaryKey(WeibarMerchantsBarrageInfo record);
}