package com.weibar.pojo.db;

import java.util.Date;

public class WeibarMerchantsBaseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.merchantid
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private Long merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.producerlogo_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String producerlogoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.qrcode_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String qrcodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.mp_name
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String mpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.merchants_name
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String merchantsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.merchants_mail
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String merchantsMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.merchants_mobile
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String merchantsMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.customercare_mobile
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String customercareMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.merchants_address
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String merchantsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.merchants_lable
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String merchantsLable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.merchants_des
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String merchantsDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.wifi_passport
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String wifiPassport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.per_capita
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String perCapita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.bar_picture
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String barPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.bar_des
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String barDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.create_time
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.update_time
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.state
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_merchants_base_info.wechat_login_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    private String wechatLoginUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.merchantid
     *
     * @return the value of weibar_merchants_base_info.merchantid
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public Long getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.merchantid
     *
     * @param merchantid the value for weibar_merchants_base_info.merchantid
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setMerchantid(Long merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.producerlogo_url
     *
     * @return the value of weibar_merchants_base_info.producerlogo_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getProducerlogoUrl() {
        return producerlogoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.producerlogo_url
     *
     * @param producerlogoUrl the value for weibar_merchants_base_info.producerlogo_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setProducerlogoUrl(String producerlogoUrl) {
        this.producerlogoUrl = producerlogoUrl == null ? null : producerlogoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.qrcode_url
     *
     * @return the value of weibar_merchants_base_info.qrcode_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.qrcode_url
     *
     * @param qrcodeUrl the value for weibar_merchants_base_info.qrcode_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.mp_name
     *
     * @return the value of weibar_merchants_base_info.mp_name
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getMpName() {
        return mpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.mp_name
     *
     * @param mpName the value for weibar_merchants_base_info.mp_name
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setMpName(String mpName) {
        this.mpName = mpName == null ? null : mpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.merchants_name
     *
     * @return the value of weibar_merchants_base_info.merchants_name
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getMerchantsName() {
        return merchantsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.merchants_name
     *
     * @param merchantsName the value for weibar_merchants_base_info.merchants_name
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setMerchantsName(String merchantsName) {
        this.merchantsName = merchantsName == null ? null : merchantsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.merchants_mail
     *
     * @return the value of weibar_merchants_base_info.merchants_mail
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getMerchantsMail() {
        return merchantsMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.merchants_mail
     *
     * @param merchantsMail the value for weibar_merchants_base_info.merchants_mail
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setMerchantsMail(String merchantsMail) {
        this.merchantsMail = merchantsMail == null ? null : merchantsMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.merchants_mobile
     *
     * @return the value of weibar_merchants_base_info.merchants_mobile
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getMerchantsMobile() {
        return merchantsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.merchants_mobile
     *
     * @param merchantsMobile the value for weibar_merchants_base_info.merchants_mobile
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setMerchantsMobile(String merchantsMobile) {
        this.merchantsMobile = merchantsMobile == null ? null : merchantsMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.customercare_mobile
     *
     * @return the value of weibar_merchants_base_info.customercare_mobile
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getCustomercareMobile() {
        return customercareMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.customercare_mobile
     *
     * @param customercareMobile the value for weibar_merchants_base_info.customercare_mobile
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setCustomercareMobile(String customercareMobile) {
        this.customercareMobile = customercareMobile == null ? null : customercareMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.merchants_address
     *
     * @return the value of weibar_merchants_base_info.merchants_address
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getMerchantsAddress() {
        return merchantsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.merchants_address
     *
     * @param merchantsAddress the value for weibar_merchants_base_info.merchants_address
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setMerchantsAddress(String merchantsAddress) {
        this.merchantsAddress = merchantsAddress == null ? null : merchantsAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.merchants_lable
     *
     * @return the value of weibar_merchants_base_info.merchants_lable
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getMerchantsLable() {
        return merchantsLable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.merchants_lable
     *
     * @param merchantsLable the value for weibar_merchants_base_info.merchants_lable
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setMerchantsLable(String merchantsLable) {
        this.merchantsLable = merchantsLable == null ? null : merchantsLable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.merchants_des
     *
     * @return the value of weibar_merchants_base_info.merchants_des
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getMerchantsDes() {
        return merchantsDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.merchants_des
     *
     * @param merchantsDes the value for weibar_merchants_base_info.merchants_des
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setMerchantsDes(String merchantsDes) {
        this.merchantsDes = merchantsDes == null ? null : merchantsDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.wifi_passport
     *
     * @return the value of weibar_merchants_base_info.wifi_passport
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getWifiPassport() {
        return wifiPassport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.wifi_passport
     *
     * @param wifiPassport the value for weibar_merchants_base_info.wifi_passport
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setWifiPassport(String wifiPassport) {
        this.wifiPassport = wifiPassport == null ? null : wifiPassport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.per_capita
     *
     * @return the value of weibar_merchants_base_info.per_capita
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getPerCapita() {
        return perCapita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.per_capita
     *
     * @param perCapita the value for weibar_merchants_base_info.per_capita
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setPerCapita(String perCapita) {
        this.perCapita = perCapita == null ? null : perCapita.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.bar_picture
     *
     * @return the value of weibar_merchants_base_info.bar_picture
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getBarPicture() {
        return barPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.bar_picture
     *
     * @param barPicture the value for weibar_merchants_base_info.bar_picture
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setBarPicture(String barPicture) {
        this.barPicture = barPicture == null ? null : barPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.bar_des
     *
     * @return the value of weibar_merchants_base_info.bar_des
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getBarDes() {
        return barDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.bar_des
     *
     * @param barDes the value for weibar_merchants_base_info.bar_des
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setBarDes(String barDes) {
        this.barDes = barDes == null ? null : barDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.create_time
     *
     * @return the value of weibar_merchants_base_info.create_time
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.create_time
     *
     * @param createTime the value for weibar_merchants_base_info.create_time
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.update_time
     *
     * @return the value of weibar_merchants_base_info.update_time
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.update_time
     *
     * @param updateTime the value for weibar_merchants_base_info.update_time
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.state
     *
     * @return the value of weibar_merchants_base_info.state
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.state
     *
     * @param state the value for weibar_merchants_base_info.state
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_merchants_base_info.wechat_login_url
     *
     * @return the value of weibar_merchants_base_info.wechat_login_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public String getWechatLoginUrl() {
        return wechatLoginUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_merchants_base_info.wechat_login_url
     *
     * @param wechatLoginUrl the value for weibar_merchants_base_info.wechat_login_url
     *
     * @mbggenerated Mon Feb 05 16:16:11 CST 2018
     */
    public void setWechatLoginUrl(String wechatLoginUrl) {
        this.wechatLoginUrl = wechatLoginUrl == null ? null : wechatLoginUrl.trim();
    }
}