package com.weibar.pojo.db;

import java.util.Date;

public class MerchantsUserBaseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants_user_base_info.user_id
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants_user_base_info.openid
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants_user_base_info.bind_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    private Date bindTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants_user_base_info.create_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants_user_base_info.update_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants_user_base_info.union_id
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    private String unionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants_user_base_info.user_id
     *
     * @return the value of merchants_user_base_info.user_id
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants_user_base_info.user_id
     *
     * @param userId the value for merchants_user_base_info.user_id
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants_user_base_info.openid
     *
     * @return the value of merchants_user_base_info.openid
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants_user_base_info.openid
     *
     * @param openid the value for merchants_user_base_info.openid
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants_user_base_info.bind_time
     *
     * @return the value of merchants_user_base_info.bind_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public Date getBindTime() {
        return bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants_user_base_info.bind_time
     *
     * @param bindTime the value for merchants_user_base_info.bind_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public void setBindTime(Date bindTime) {
        this.bindTime = bindTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants_user_base_info.create_time
     *
     * @return the value of merchants_user_base_info.create_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants_user_base_info.create_time
     *
     * @param createTime the value for merchants_user_base_info.create_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants_user_base_info.update_time
     *
     * @return the value of merchants_user_base_info.update_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants_user_base_info.update_time
     *
     * @param updateTime the value for merchants_user_base_info.update_time
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants_user_base_info.union_id
     *
     * @return the value of merchants_user_base_info.union_id
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants_user_base_info.union_id
     *
     * @param unionId the value for merchants_user_base_info.union_id
     *
     * @mbggenerated Thu Mar 29 15:05:40 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }
}