package com.weibar.pojo.db;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserRechargeOrderCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public UserRechargeOrderCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andChorderidIsNull() {
            addCriterion("chorderid is null");
            return (Criteria) this;
        }

        public Criteria andChorderidIsNotNull() {
            addCriterion("chorderid is not null");
            return (Criteria) this;
        }

        public Criteria andChorderidEqualTo(String value) {
            addCriterion("chorderid =", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidNotEqualTo(String value) {
            addCriterion("chorderid <>", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidGreaterThan(String value) {
            addCriterion("chorderid >", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidGreaterThanOrEqualTo(String value) {
            addCriterion("chorderid >=", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidLessThan(String value) {
            addCriterion("chorderid <", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidLessThanOrEqualTo(String value) {
            addCriterion("chorderid <=", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidLike(String value) {
            addCriterion("chorderid like", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidNotLike(String value) {
            addCriterion("chorderid not like", value, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidIn(List<String> values) {
            addCriterion("chorderid in", values, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidNotIn(List<String> values) {
            addCriterion("chorderid not in", values, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidBetween(String value1, String value2) {
            addCriterion("chorderid between", value1, value2, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChorderidNotBetween(String value1, String value2) {
            addCriterion("chorderid not between", value1, value2, "chorderid");
            return (Criteria) this;
        }

        public Criteria andChTpyeIsNull() {
            addCriterion("ch_tpye is null");
            return (Criteria) this;
        }

        public Criteria andChTpyeIsNotNull() {
            addCriterion("ch_tpye is not null");
            return (Criteria) this;
        }

        public Criteria andChTpyeEqualTo(Integer value) {
            addCriterion("ch_tpye =", value, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeNotEqualTo(Integer value) {
            addCriterion("ch_tpye <>", value, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeGreaterThan(Integer value) {
            addCriterion("ch_tpye >", value, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ch_tpye >=", value, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeLessThan(Integer value) {
            addCriterion("ch_tpye <", value, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeLessThanOrEqualTo(Integer value) {
            addCriterion("ch_tpye <=", value, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeIn(List<Integer> values) {
            addCriterion("ch_tpye in", values, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeNotIn(List<Integer> values) {
            addCriterion("ch_tpye not in", values, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeBetween(Integer value1, Integer value2) {
            addCriterion("ch_tpye between", value1, value2, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChTpyeNotBetween(Integer value1, Integer value2) {
            addCriterion("ch_tpye not between", value1, value2, "chTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeIsNull() {
            addCriterion("ch_bank_tpye is null");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeIsNotNull() {
            addCriterion("ch_bank_tpye is not null");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeEqualTo(String value) {
            addCriterion("ch_bank_tpye =", value, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeNotEqualTo(String value) {
            addCriterion("ch_bank_tpye <>", value, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeGreaterThan(String value) {
            addCriterion("ch_bank_tpye >", value, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeGreaterThanOrEqualTo(String value) {
            addCriterion("ch_bank_tpye >=", value, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeLessThan(String value) {
            addCriterion("ch_bank_tpye <", value, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeLessThanOrEqualTo(String value) {
            addCriterion("ch_bank_tpye <=", value, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeLike(String value) {
            addCriterion("ch_bank_tpye like", value, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeNotLike(String value) {
            addCriterion("ch_bank_tpye not like", value, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeIn(List<String> values) {
            addCriterion("ch_bank_tpye in", values, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeNotIn(List<String> values) {
            addCriterion("ch_bank_tpye not in", values, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeBetween(String value1, String value2) {
            addCriterion("ch_bank_tpye between", value1, value2, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeNotBetween(String value1, String value2) {
            addCriterion("ch_bank_tpye not between", value1, value2, "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNull() {
            addCriterion("total_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNotNull() {
            addCriterion("total_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeEqualTo(Integer value) {
            addCriterion("total_fee =", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotEqualTo(Integer value) {
            addCriterion("total_fee <>", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThan(Integer value) {
            addCriterion("total_fee >", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_fee >=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThan(Integer value) {
            addCriterion("total_fee <", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThanOrEqualTo(Integer value) {
            addCriterion("total_fee <=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIn(List<Integer> values) {
            addCriterion("total_fee in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotIn(List<Integer> values) {
            addCriterion("total_fee not in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeBetween(Integer value1, Integer value2) {
            addCriterion("total_fee between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_fee not between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andChaccountIsNull() {
            addCriterion("chaccount is null");
            return (Criteria) this;
        }

        public Criteria andChaccountIsNotNull() {
            addCriterion("chaccount is not null");
            return (Criteria) this;
        }

        public Criteria andChaccountEqualTo(String value) {
            addCriterion("chaccount =", value, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountNotEqualTo(String value) {
            addCriterion("chaccount <>", value, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountGreaterThan(String value) {
            addCriterion("chaccount >", value, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountGreaterThanOrEqualTo(String value) {
            addCriterion("chaccount >=", value, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountLessThan(String value) {
            addCriterion("chaccount <", value, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountLessThanOrEqualTo(String value) {
            addCriterion("chaccount <=", value, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountLike(String value) {
            addCriterion("chaccount like", value, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountNotLike(String value) {
            addCriterion("chaccount not like", value, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountIn(List<String> values) {
            addCriterion("chaccount in", values, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountNotIn(List<String> values) {
            addCriterion("chaccount not in", values, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountBetween(String value1, String value2) {
            addCriterion("chaccount between", value1, value2, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChaccountNotBetween(String value1, String value2) {
            addCriterion("chaccount not between", value1, value2, "chaccount");
            return (Criteria) this;
        }

        public Criteria andChappIdIsNull() {
            addCriterion("chapp_id is null");
            return (Criteria) this;
        }

        public Criteria andChappIdIsNotNull() {
            addCriterion("chapp_id is not null");
            return (Criteria) this;
        }

        public Criteria andChappIdEqualTo(String value) {
            addCriterion("chapp_id =", value, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdNotEqualTo(String value) {
            addCriterion("chapp_id <>", value, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdGreaterThan(String value) {
            addCriterion("chapp_id >", value, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdGreaterThanOrEqualTo(String value) {
            addCriterion("chapp_id >=", value, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdLessThan(String value) {
            addCriterion("chapp_id <", value, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdLessThanOrEqualTo(String value) {
            addCriterion("chapp_id <=", value, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdLike(String value) {
            addCriterion("chapp_id like", value, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdNotLike(String value) {
            addCriterion("chapp_id not like", value, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdIn(List<String> values) {
            addCriterion("chapp_id in", values, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdNotIn(List<String> values) {
            addCriterion("chapp_id not in", values, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdBetween(String value1, String value2) {
            addCriterion("chapp_id between", value1, value2, "chappId");
            return (Criteria) this;
        }

        public Criteria andChappIdNotBetween(String value1, String value2) {
            addCriterion("chapp_id not between", value1, value2, "chappId");
            return (Criteria) this;
        }

        public Criteria andChmethodIsNull() {
            addCriterion("chmethod is null");
            return (Criteria) this;
        }

        public Criteria andChmethodIsNotNull() {
            addCriterion("chmethod is not null");
            return (Criteria) this;
        }

        public Criteria andChmethodEqualTo(String value) {
            addCriterion("chmethod =", value, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodNotEqualTo(String value) {
            addCriterion("chmethod <>", value, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodGreaterThan(String value) {
            addCriterion("chmethod >", value, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodGreaterThanOrEqualTo(String value) {
            addCriterion("chmethod >=", value, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodLessThan(String value) {
            addCriterion("chmethod <", value, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodLessThanOrEqualTo(String value) {
            addCriterion("chmethod <=", value, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodLike(String value) {
            addCriterion("chmethod like", value, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodNotLike(String value) {
            addCriterion("chmethod not like", value, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodIn(List<String> values) {
            addCriterion("chmethod in", values, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodNotIn(List<String> values) {
            addCriterion("chmethod not in", values, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodBetween(String value1, String value2) {
            addCriterion("chmethod between", value1, value2, "chmethod");
            return (Criteria) this;
        }

        public Criteria andChmethodNotBetween(String value1, String value2) {
            addCriterion("chmethod not between", value1, value2, "chmethod");
            return (Criteria) this;
        }

        public Criteria andUserIpIsNull() {
            addCriterion("user_ip is null");
            return (Criteria) this;
        }

        public Criteria andUserIpIsNotNull() {
            addCriterion("user_ip is not null");
            return (Criteria) this;
        }

        public Criteria andUserIpEqualTo(String value) {
            addCriterion("user_ip =", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpNotEqualTo(String value) {
            addCriterion("user_ip <>", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpGreaterThan(String value) {
            addCriterion("user_ip >", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpGreaterThanOrEqualTo(String value) {
            addCriterion("user_ip >=", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpLessThan(String value) {
            addCriterion("user_ip <", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpLessThanOrEqualTo(String value) {
            addCriterion("user_ip <=", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpLike(String value) {
            addCriterion("user_ip like", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpNotLike(String value) {
            addCriterion("user_ip not like", value, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpIn(List<String> values) {
            addCriterion("user_ip in", values, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpNotIn(List<String> values) {
            addCriterion("user_ip not in", values, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpBetween(String value1, String value2) {
            addCriterion("user_ip between", value1, value2, "userIp");
            return (Criteria) this;
        }

        public Criteria andUserIpNotBetween(String value1, String value2) {
            addCriterion("user_ip not between", value1, value2, "userIp");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andChStatusIsNull() {
            addCriterion("ch_status is null");
            return (Criteria) this;
        }

        public Criteria andChStatusIsNotNull() {
            addCriterion("ch_status is not null");
            return (Criteria) this;
        }

        public Criteria andChStatusEqualTo(String value) {
            addCriterion("ch_status =", value, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusNotEqualTo(String value) {
            addCriterion("ch_status <>", value, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusGreaterThan(String value) {
            addCriterion("ch_status >", value, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ch_status >=", value, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusLessThan(String value) {
            addCriterion("ch_status <", value, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusLessThanOrEqualTo(String value) {
            addCriterion("ch_status <=", value, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusLike(String value) {
            addCriterion("ch_status like", value, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusNotLike(String value) {
            addCriterion("ch_status not like", value, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusIn(List<String> values) {
            addCriterion("ch_status in", values, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusNotIn(List<String> values) {
            addCriterion("ch_status not in", values, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusBetween(String value1, String value2) {
            addCriterion("ch_status between", value1, value2, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusNotBetween(String value1, String value2) {
            addCriterion("ch_status not between", value1, value2, "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgIsNull() {
            addCriterion("ch_statusMsg is null");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgIsNotNull() {
            addCriterion("ch_statusMsg is not null");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgEqualTo(String value) {
            addCriterion("ch_statusMsg =", value, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgNotEqualTo(String value) {
            addCriterion("ch_statusMsg <>", value, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgGreaterThan(String value) {
            addCriterion("ch_statusMsg >", value, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgGreaterThanOrEqualTo(String value) {
            addCriterion("ch_statusMsg >=", value, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgLessThan(String value) {
            addCriterion("ch_statusMsg <", value, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgLessThanOrEqualTo(String value) {
            addCriterion("ch_statusMsg <=", value, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgLike(String value) {
            addCriterion("ch_statusMsg like", value, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgNotLike(String value) {
            addCriterion("ch_statusMsg not like", value, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgIn(List<String> values) {
            addCriterion("ch_statusMsg in", values, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgNotIn(List<String> values) {
            addCriterion("ch_statusMsg not in", values, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgBetween(String value1, String value2) {
            addCriterion("ch_statusMsg between", value1, value2, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgNotBetween(String value1, String value2) {
            addCriterion("ch_statusMsg not between", value1, value2, "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeIsNull() {
            addCriterion("pay_comp_time is null");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeIsNotNull() {
            addCriterion("pay_comp_time is not null");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeEqualTo(Date value) {
            addCriterion("pay_comp_time =", value, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeNotEqualTo(Date value) {
            addCriterion("pay_comp_time <>", value, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeGreaterThan(Date value) {
            addCriterion("pay_comp_time >", value, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pay_comp_time >=", value, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeLessThan(Date value) {
            addCriterion("pay_comp_time <", value, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeLessThanOrEqualTo(Date value) {
            addCriterion("pay_comp_time <=", value, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeIn(List<Date> values) {
            addCriterion("pay_comp_time in", values, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeNotIn(List<Date> values) {
            addCriterion("pay_comp_time not in", values, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeBetween(Date value1, Date value2) {
            addCriterion("pay_comp_time between", value1, value2, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andPayCompTimeNotBetween(Date value1, Date value2) {
            addCriterion("pay_comp_time not between", value1, value2, "payCompTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andExt1IsNull() {
            addCriterion("ext1 is null");
            return (Criteria) this;
        }

        public Criteria andExt1IsNotNull() {
            addCriterion("ext1 is not null");
            return (Criteria) this;
        }

        public Criteria andExt1EqualTo(String value) {
            addCriterion("ext1 =", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotEqualTo(String value) {
            addCriterion("ext1 <>", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1GreaterThan(String value) {
            addCriterion("ext1 >", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1GreaterThanOrEqualTo(String value) {
            addCriterion("ext1 >=", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1LessThan(String value) {
            addCriterion("ext1 <", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1LessThanOrEqualTo(String value) {
            addCriterion("ext1 <=", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1Like(String value) {
            addCriterion("ext1 like", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotLike(String value) {
            addCriterion("ext1 not like", value, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1In(List<String> values) {
            addCriterion("ext1 in", values, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotIn(List<String> values) {
            addCriterion("ext1 not in", values, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1Between(String value1, String value2) {
            addCriterion("ext1 between", value1, value2, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt1NotBetween(String value1, String value2) {
            addCriterion("ext1 not between", value1, value2, "ext1");
            return (Criteria) this;
        }

        public Criteria andExt2IsNull() {
            addCriterion("ext2 is null");
            return (Criteria) this;
        }

        public Criteria andExt2IsNotNull() {
            addCriterion("ext2 is not null");
            return (Criteria) this;
        }

        public Criteria andExt2EqualTo(String value) {
            addCriterion("ext2 =", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotEqualTo(String value) {
            addCriterion("ext2 <>", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2GreaterThan(String value) {
            addCriterion("ext2 >", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2GreaterThanOrEqualTo(String value) {
            addCriterion("ext2 >=", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2LessThan(String value) {
            addCriterion("ext2 <", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2LessThanOrEqualTo(String value) {
            addCriterion("ext2 <=", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2Like(String value) {
            addCriterion("ext2 like", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotLike(String value) {
            addCriterion("ext2 not like", value, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2In(List<String> values) {
            addCriterion("ext2 in", values, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotIn(List<String> values) {
            addCriterion("ext2 not in", values, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2Between(String value1, String value2) {
            addCriterion("ext2 between", value1, value2, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt2NotBetween(String value1, String value2) {
            addCriterion("ext2 not between", value1, value2, "ext2");
            return (Criteria) this;
        }

        public Criteria andExt3IsNull() {
            addCriterion("ext3 is null");
            return (Criteria) this;
        }

        public Criteria andExt3IsNotNull() {
            addCriterion("ext3 is not null");
            return (Criteria) this;
        }

        public Criteria andExt3EqualTo(BigDecimal value) {
            addCriterion("ext3 =", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotEqualTo(BigDecimal value) {
            addCriterion("ext3 <>", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3GreaterThan(BigDecimal value) {
            addCriterion("ext3 >", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ext3 >=", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3LessThan(BigDecimal value) {
            addCriterion("ext3 <", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3LessThanOrEqualTo(BigDecimal value) {
            addCriterion("ext3 <=", value, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3In(List<BigDecimal> values) {
            addCriterion("ext3 in", values, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotIn(List<BigDecimal> values) {
            addCriterion("ext3 not in", values, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("ext3 between", value1, value2, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt3NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ext3 not between", value1, value2, "ext3");
            return (Criteria) this;
        }

        public Criteria andExt4IsNull() {
            addCriterion("ext4 is null");
            return (Criteria) this;
        }

        public Criteria andExt4IsNotNull() {
            addCriterion("ext4 is not null");
            return (Criteria) this;
        }

        public Criteria andExt4EqualTo(Date value) {
            addCriterion("ext4 =", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotEqualTo(Date value) {
            addCriterion("ext4 <>", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4GreaterThan(Date value) {
            addCriterion("ext4 >", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4GreaterThanOrEqualTo(Date value) {
            addCriterion("ext4 >=", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4LessThan(Date value) {
            addCriterion("ext4 <", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4LessThanOrEqualTo(Date value) {
            addCriterion("ext4 <=", value, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4In(List<Date> values) {
            addCriterion("ext4 in", values, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotIn(List<Date> values) {
            addCriterion("ext4 not in", values, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4Between(Date value1, Date value2) {
            addCriterion("ext4 between", value1, value2, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt4NotBetween(Date value1, Date value2) {
            addCriterion("ext4 not between", value1, value2, "ext4");
            return (Criteria) this;
        }

        public Criteria andExt5IsNull() {
            addCriterion("ext5 is null");
            return (Criteria) this;
        }

        public Criteria andExt5IsNotNull() {
            addCriterion("ext5 is not null");
            return (Criteria) this;
        }

        public Criteria andExt5EqualTo(Integer value) {
            addCriterion("ext5 =", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotEqualTo(Integer value) {
            addCriterion("ext5 <>", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5GreaterThan(Integer value) {
            addCriterion("ext5 >", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5GreaterThanOrEqualTo(Integer value) {
            addCriterion("ext5 >=", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5LessThan(Integer value) {
            addCriterion("ext5 <", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5LessThanOrEqualTo(Integer value) {
            addCriterion("ext5 <=", value, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5In(List<Integer> values) {
            addCriterion("ext5 in", values, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotIn(List<Integer> values) {
            addCriterion("ext5 not in", values, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5Between(Integer value1, Integer value2) {
            addCriterion("ext5 between", value1, value2, "ext5");
            return (Criteria) this;
        }

        public Criteria andExt5NotBetween(Integer value1, Integer value2) {
            addCriterion("ext5 not between", value1, value2, "ext5");
            return (Criteria) this;
        }

        public Criteria andOrderIdLikeInsensitive(String value) {
            addCriterion("upper(order_id) like", value.toUpperCase(), "orderId");
            return (Criteria) this;
        }

        public Criteria andOpenidLikeInsensitive(String value) {
            addCriterion("upper(openid) like", value.toUpperCase(), "openid");
            return (Criteria) this;
        }

        public Criteria andChorderidLikeInsensitive(String value) {
            addCriterion("upper(chorderid) like", value.toUpperCase(), "chorderid");
            return (Criteria) this;
        }

        public Criteria andChBankTpyeLikeInsensitive(String value) {
            addCriterion("upper(ch_bank_tpye) like", value.toUpperCase(), "chBankTpye");
            return (Criteria) this;
        }

        public Criteria andChaccountLikeInsensitive(String value) {
            addCriterion("upper(chaccount) like", value.toUpperCase(), "chaccount");
            return (Criteria) this;
        }

        public Criteria andChappIdLikeInsensitive(String value) {
            addCriterion("upper(chapp_id) like", value.toUpperCase(), "chappId");
            return (Criteria) this;
        }

        public Criteria andChmethodLikeInsensitive(String value) {
            addCriterion("upper(chmethod) like", value.toUpperCase(), "chmethod");
            return (Criteria) this;
        }

        public Criteria andUserIpLikeInsensitive(String value) {
            addCriterion("upper(user_ip) like", value.toUpperCase(), "userIp");
            return (Criteria) this;
        }

        public Criteria andChStatusLikeInsensitive(String value) {
            addCriterion("upper(ch_status) like", value.toUpperCase(), "chStatus");
            return (Criteria) this;
        }

        public Criteria andChStatusmsgLikeInsensitive(String value) {
            addCriterion("upper(ch_statusMsg) like", value.toUpperCase(), "chStatusmsg");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("upper(description) like", value.toUpperCase(), "description");
            return (Criteria) this;
        }

        public Criteria andExt1LikeInsensitive(String value) {
            addCriterion("upper(ext1) like", value.toUpperCase(), "ext1");
            return (Criteria) this;
        }

        public Criteria andExt2LikeInsensitive(String value) {
            addCriterion("upper(ext2) like", value.toUpperCase(), "ext2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_recharge_order
     *
     * @mbggenerated do_not_delete_during_merge Sun Feb 11 14:37:42 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_recharge_order
     *
     * @mbggenerated Sun Feb 11 14:37:42 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}