package com.weibar.pojo.db;

import java.math.BigDecimal;
import java.util.Date;

public class WeibarRedpackageDeposit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.id
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.redpackageid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Long redpackageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.openid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.user_id
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.amount
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.sendnumber
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Integer sendnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.getnumber
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Integer getnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.redPacketTitle
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private String redpackettitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.merchantid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Long merchantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.status
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.create_time
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_redpackage_deposit.update_time
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.id
     *
     * @return the value of weibar_redpackage_deposit.id
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.id
     *
     * @param id the value for weibar_redpackage_deposit.id
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.redpackageid
     *
     * @return the value of weibar_redpackage_deposit.redpackageid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Long getRedpackageid() {
        return redpackageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.redpackageid
     *
     * @param redpackageid the value for weibar_redpackage_deposit.redpackageid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setRedpackageid(Long redpackageid) {
        this.redpackageid = redpackageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.openid
     *
     * @return the value of weibar_redpackage_deposit.openid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.openid
     *
     * @param openid the value for weibar_redpackage_deposit.openid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.user_id
     *
     * @return the value of weibar_redpackage_deposit.user_id
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.user_id
     *
     * @param userId the value for weibar_redpackage_deposit.user_id
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.amount
     *
     * @return the value of weibar_redpackage_deposit.amount
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.amount
     *
     * @param amount the value for weibar_redpackage_deposit.amount
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.sendnumber
     *
     * @return the value of weibar_redpackage_deposit.sendnumber
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Integer getSendnumber() {
        return sendnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.sendnumber
     *
     * @param sendnumber the value for weibar_redpackage_deposit.sendnumber
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setSendnumber(Integer sendnumber) {
        this.sendnumber = sendnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.getnumber
     *
     * @return the value of weibar_redpackage_deposit.getnumber
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Integer getGetnumber() {
        return getnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.getnumber
     *
     * @param getnumber the value for weibar_redpackage_deposit.getnumber
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setGetnumber(Integer getnumber) {
        this.getnumber = getnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.redPacketTitle
     *
     * @return the value of weibar_redpackage_deposit.redPacketTitle
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public String getRedpackettitle() {
        return redpackettitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.redPacketTitle
     *
     * @param redpackettitle the value for weibar_redpackage_deposit.redPacketTitle
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setRedpackettitle(String redpackettitle) {
        this.redpackettitle = redpackettitle == null ? null : redpackettitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.merchantid
     *
     * @return the value of weibar_redpackage_deposit.merchantid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Long getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.merchantid
     *
     * @param merchantid the value for weibar_redpackage_deposit.merchantid
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setMerchantid(Long merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.status
     *
     * @return the value of weibar_redpackage_deposit.status
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.status
     *
     * @param status the value for weibar_redpackage_deposit.status
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.create_time
     *
     * @return the value of weibar_redpackage_deposit.create_time
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.create_time
     *
     * @param createTime the value for weibar_redpackage_deposit.create_time
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_redpackage_deposit.update_time
     *
     * @return the value of weibar_redpackage_deposit.update_time
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_redpackage_deposit.update_time
     *
     * @param updateTime the value for weibar_redpackage_deposit.update_time
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}