package com.weibar.pojo.db;

import java.util.Date;

public class WeibarPrivateChatIdMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_private_chat_id_map.chat_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    private Long chatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_private_chat_id_map.from_user_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    private Long fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_private_chat_id_map.to_user_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    private Long toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_private_chat_id_map.create_time
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weibar_private_chat_id_map.update_time
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_private_chat_id_map.chat_id
     *
     * @return the value of weibar_private_chat_id_map.chat_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public Long getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_private_chat_id_map.chat_id
     *
     * @param chatId the value for weibar_private_chat_id_map.chat_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_private_chat_id_map.from_user_id
     *
     * @return the value of weibar_private_chat_id_map.from_user_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public Long getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_private_chat_id_map.from_user_id
     *
     * @param fromUserId the value for weibar_private_chat_id_map.from_user_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public void setFromUserId(Long fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_private_chat_id_map.to_user_id
     *
     * @return the value of weibar_private_chat_id_map.to_user_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_private_chat_id_map.to_user_id
     *
     * @param toUserId the value for weibar_private_chat_id_map.to_user_id
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_private_chat_id_map.create_time
     *
     * @return the value of weibar_private_chat_id_map.create_time
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_private_chat_id_map.create_time
     *
     * @param createTime the value for weibar_private_chat_id_map.create_time
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weibar_private_chat_id_map.update_time
     *
     * @return the value of weibar_private_chat_id_map.update_time
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weibar_private_chat_id_map.update_time
     *
     * @param updateTime the value for weibar_private_chat_id_map.update_time
     *
     * @mbggenerated Wed Mar 28 18:05:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}