package com.weibar.pojo.db;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeibarMerchantsBarrageSettingInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public WeibarMerchantsBarrageSettingInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMerchantidIsNull() {
            addCriterion("merchantid is null");
            return (Criteria) this;
        }

        public Criteria andMerchantidIsNotNull() {
            addCriterion("merchantid is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantidEqualTo(Long value) {
            addCriterion("merchantid =", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidNotEqualTo(Long value) {
            addCriterion("merchantid <>", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidGreaterThan(Long value) {
            addCriterion("merchantid >", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidGreaterThanOrEqualTo(Long value) {
            addCriterion("merchantid >=", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidLessThan(Long value) {
            addCriterion("merchantid <", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidLessThanOrEqualTo(Long value) {
            addCriterion("merchantid <=", value, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidIn(List<Long> values) {
            addCriterion("merchantid in", values, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidNotIn(List<Long> values) {
            addCriterion("merchantid not in", values, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidBetween(Long value1, Long value2) {
            addCriterion("merchantid between", value1, value2, "merchantid");
            return (Criteria) this;
        }

        public Criteria andMerchantidNotBetween(Long value1, Long value2) {
            addCriterion("merchantid not between", value1, value2, "merchantid");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnIsNull() {
            addCriterion("barrage_turn_on is null");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnIsNotNull() {
            addCriterion("barrage_turn_on is not null");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnEqualTo(String value) {
            addCriterion("barrage_turn_on =", value, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnNotEqualTo(String value) {
            addCriterion("barrage_turn_on <>", value, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnGreaterThan(String value) {
            addCriterion("barrage_turn_on >", value, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnGreaterThanOrEqualTo(String value) {
            addCriterion("barrage_turn_on >=", value, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnLessThan(String value) {
            addCriterion("barrage_turn_on <", value, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnLessThanOrEqualTo(String value) {
            addCriterion("barrage_turn_on <=", value, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnLike(String value) {
            addCriterion("barrage_turn_on like", value, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnNotLike(String value) {
            addCriterion("barrage_turn_on not like", value, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnIn(List<String> values) {
            addCriterion("barrage_turn_on in", values, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnNotIn(List<String> values) {
            addCriterion("barrage_turn_on not in", values, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnBetween(String value1, String value2) {
            addCriterion("barrage_turn_on between", value1, value2, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnNotBetween(String value1, String value2) {
            addCriterion("barrage_turn_on not between", value1, value2, "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnIsNull() {
            addCriterion("loop_turn_on is null");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnIsNotNull() {
            addCriterion("loop_turn_on is not null");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnEqualTo(String value) {
            addCriterion("loop_turn_on =", value, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnNotEqualTo(String value) {
            addCriterion("loop_turn_on <>", value, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnGreaterThan(String value) {
            addCriterion("loop_turn_on >", value, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnGreaterThanOrEqualTo(String value) {
            addCriterion("loop_turn_on >=", value, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnLessThan(String value) {
            addCriterion("loop_turn_on <", value, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnLessThanOrEqualTo(String value) {
            addCriterion("loop_turn_on <=", value, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnLike(String value) {
            addCriterion("loop_turn_on like", value, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnNotLike(String value) {
            addCriterion("loop_turn_on not like", value, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnIn(List<String> values) {
            addCriterion("loop_turn_on in", values, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnNotIn(List<String> values) {
            addCriterion("loop_turn_on not in", values, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnBetween(String value1, String value2) {
            addCriterion("loop_turn_on between", value1, value2, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnNotBetween(String value1, String value2) {
            addCriterion("loop_turn_on not between", value1, value2, "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnIsNull() {
            addCriterion("sytle_turn_on is null");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnIsNotNull() {
            addCriterion("sytle_turn_on is not null");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnEqualTo(String value) {
            addCriterion("sytle_turn_on =", value, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnNotEqualTo(String value) {
            addCriterion("sytle_turn_on <>", value, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnGreaterThan(String value) {
            addCriterion("sytle_turn_on >", value, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnGreaterThanOrEqualTo(String value) {
            addCriterion("sytle_turn_on >=", value, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnLessThan(String value) {
            addCriterion("sytle_turn_on <", value, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnLessThanOrEqualTo(String value) {
            addCriterion("sytle_turn_on <=", value, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnLike(String value) {
            addCriterion("sytle_turn_on like", value, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnNotLike(String value) {
            addCriterion("sytle_turn_on not like", value, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnIn(List<String> values) {
            addCriterion("sytle_turn_on in", values, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnNotIn(List<String> values) {
            addCriterion("sytle_turn_on not in", values, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnBetween(String value1, String value2) {
            addCriterion("sytle_turn_on between", value1, value2, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnNotBetween(String value1, String value2) {
            addCriterion("sytle_turn_on not between", value1, value2, "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnIsNull() {
            addCriterion("sheer_turn_on is null");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnIsNotNull() {
            addCriterion("sheer_turn_on is not null");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnEqualTo(String value) {
            addCriterion("sheer_turn_on =", value, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnNotEqualTo(String value) {
            addCriterion("sheer_turn_on <>", value, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnGreaterThan(String value) {
            addCriterion("sheer_turn_on >", value, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnGreaterThanOrEqualTo(String value) {
            addCriterion("sheer_turn_on >=", value, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnLessThan(String value) {
            addCriterion("sheer_turn_on <", value, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnLessThanOrEqualTo(String value) {
            addCriterion("sheer_turn_on <=", value, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnLike(String value) {
            addCriterion("sheer_turn_on like", value, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnNotLike(String value) {
            addCriterion("sheer_turn_on not like", value, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnIn(List<String> values) {
            addCriterion("sheer_turn_on in", values, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnNotIn(List<String> values) {
            addCriterion("sheer_turn_on not in", values, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnBetween(String value1, String value2) {
            addCriterion("sheer_turn_on between", value1, value2, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnNotBetween(String value1, String value2) {
            addCriterion("sheer_turn_on not between", value1, value2, "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnIsNull() {
            addCriterion("richman_turn_on is null");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnIsNotNull() {
            addCriterion("richman_turn_on is not null");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnEqualTo(String value) {
            addCriterion("richman_turn_on =", value, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnNotEqualTo(String value) {
            addCriterion("richman_turn_on <>", value, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnGreaterThan(String value) {
            addCriterion("richman_turn_on >", value, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnGreaterThanOrEqualTo(String value) {
            addCriterion("richman_turn_on >=", value, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnLessThan(String value) {
            addCriterion("richman_turn_on <", value, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnLessThanOrEqualTo(String value) {
            addCriterion("richman_turn_on <=", value, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnLike(String value) {
            addCriterion("richman_turn_on like", value, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnNotLike(String value) {
            addCriterion("richman_turn_on not like", value, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnIn(List<String> values) {
            addCriterion("richman_turn_on in", values, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnNotIn(List<String> values) {
            addCriterion("richman_turn_on not in", values, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnBetween(String value1, String value2) {
            addCriterion("richman_turn_on between", value1, value2, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnNotBetween(String value1, String value2) {
            addCriterion("richman_turn_on not between", value1, value2, "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnIsNull() {
            addCriterion("qrcode_turn_on is null");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnIsNotNull() {
            addCriterion("qrcode_turn_on is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnEqualTo(String value) {
            addCriterion("qrcode_turn_on =", value, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnNotEqualTo(String value) {
            addCriterion("qrcode_turn_on <>", value, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnGreaterThan(String value) {
            addCriterion("qrcode_turn_on >", value, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnGreaterThanOrEqualTo(String value) {
            addCriterion("qrcode_turn_on >=", value, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnLessThan(String value) {
            addCriterion("qrcode_turn_on <", value, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnLessThanOrEqualTo(String value) {
            addCriterion("qrcode_turn_on <=", value, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnLike(String value) {
            addCriterion("qrcode_turn_on like", value, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnNotLike(String value) {
            addCriterion("qrcode_turn_on not like", value, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnIn(List<String> values) {
            addCriterion("qrcode_turn_on in", values, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnNotIn(List<String> values) {
            addCriterion("qrcode_turn_on not in", values, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnBetween(String value1, String value2) {
            addCriterion("qrcode_turn_on between", value1, value2, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnNotBetween(String value1, String value2) {
            addCriterion("qrcode_turn_on not between", value1, value2, "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleIsNull() {
            addCriterion("qrcode_light_sytle is null");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleIsNotNull() {
            addCriterion("qrcode_light_sytle is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleEqualTo(String value) {
            addCriterion("qrcode_light_sytle =", value, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleNotEqualTo(String value) {
            addCriterion("qrcode_light_sytle <>", value, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleGreaterThan(String value) {
            addCriterion("qrcode_light_sytle >", value, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleGreaterThanOrEqualTo(String value) {
            addCriterion("qrcode_light_sytle >=", value, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleLessThan(String value) {
            addCriterion("qrcode_light_sytle <", value, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleLessThanOrEqualTo(String value) {
            addCriterion("qrcode_light_sytle <=", value, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleLike(String value) {
            addCriterion("qrcode_light_sytle like", value, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleNotLike(String value) {
            addCriterion("qrcode_light_sytle not like", value, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleIn(List<String> values) {
            addCriterion("qrcode_light_sytle in", values, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleNotIn(List<String> values) {
            addCriterion("qrcode_light_sytle not in", values, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleBetween(String value1, String value2) {
            addCriterion("qrcode_light_sytle between", value1, value2, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleNotBetween(String value1, String value2) {
            addCriterion("qrcode_light_sytle not between", value1, value2, "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleIsNull() {
            addCriterion("barrage_font_sytle is null");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleIsNotNull() {
            addCriterion("barrage_font_sytle is not null");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleEqualTo(String value) {
            addCriterion("barrage_font_sytle =", value, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleNotEqualTo(String value) {
            addCriterion("barrage_font_sytle <>", value, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleGreaterThan(String value) {
            addCriterion("barrage_font_sytle >", value, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleGreaterThanOrEqualTo(String value) {
            addCriterion("barrage_font_sytle >=", value, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleLessThan(String value) {
            addCriterion("barrage_font_sytle <", value, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleLessThanOrEqualTo(String value) {
            addCriterion("barrage_font_sytle <=", value, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleLike(String value) {
            addCriterion("barrage_font_sytle like", value, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleNotLike(String value) {
            addCriterion("barrage_font_sytle not like", value, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleIn(List<String> values) {
            addCriterion("barrage_font_sytle in", values, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleNotIn(List<String> values) {
            addCriterion("barrage_font_sytle not in", values, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleBetween(String value1, String value2) {
            addCriterion("barrage_font_sytle between", value1, value2, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleNotBetween(String value1, String value2) {
            addCriterion("barrage_font_sytle not between", value1, value2, "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleIsNull() {
            addCriterion("holdscreen_font_sytle is null");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleIsNotNull() {
            addCriterion("holdscreen_font_sytle is not null");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleEqualTo(String value) {
            addCriterion("holdscreen_font_sytle =", value, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleNotEqualTo(String value) {
            addCriterion("holdscreen_font_sytle <>", value, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleGreaterThan(String value) {
            addCriterion("holdscreen_font_sytle >", value, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleGreaterThanOrEqualTo(String value) {
            addCriterion("holdscreen_font_sytle >=", value, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleLessThan(String value) {
            addCriterion("holdscreen_font_sytle <", value, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleLessThanOrEqualTo(String value) {
            addCriterion("holdscreen_font_sytle <=", value, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleLike(String value) {
            addCriterion("holdscreen_font_sytle like", value, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleNotLike(String value) {
            addCriterion("holdscreen_font_sytle not like", value, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleIn(List<String> values) {
            addCriterion("holdscreen_font_sytle in", values, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleNotIn(List<String> values) {
            addCriterion("holdscreen_font_sytle not in", values, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleBetween(String value1, String value2) {
            addCriterion("holdscreen_font_sytle between", value1, value2, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleNotBetween(String value1, String value2) {
            addCriterion("holdscreen_font_sytle not between", value1, value2, "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleIsNull() {
            addCriterion("barrage_move_sytle is null");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleIsNotNull() {
            addCriterion("barrage_move_sytle is not null");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleEqualTo(String value) {
            addCriterion("barrage_move_sytle =", value, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleNotEqualTo(String value) {
            addCriterion("barrage_move_sytle <>", value, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleGreaterThan(String value) {
            addCriterion("barrage_move_sytle >", value, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleGreaterThanOrEqualTo(String value) {
            addCriterion("barrage_move_sytle >=", value, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleLessThan(String value) {
            addCriterion("barrage_move_sytle <", value, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleLessThanOrEqualTo(String value) {
            addCriterion("barrage_move_sytle <=", value, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleLike(String value) {
            addCriterion("barrage_move_sytle like", value, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleNotLike(String value) {
            addCriterion("barrage_move_sytle not like", value, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleIn(List<String> values) {
            addCriterion("barrage_move_sytle in", values, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleNotIn(List<String> values) {
            addCriterion("barrage_move_sytle not in", values, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleBetween(String value1, String value2) {
            addCriterion("barrage_move_sytle between", value1, value2, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleNotBetween(String value1, String value2) {
            addCriterion("barrage_move_sytle not between", value1, value2, "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleIsNull() {
            addCriterion("bg_light_sytle is null");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleIsNotNull() {
            addCriterion("bg_light_sytle is not null");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleEqualTo(String value) {
            addCriterion("bg_light_sytle =", value, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleNotEqualTo(String value) {
            addCriterion("bg_light_sytle <>", value, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleGreaterThan(String value) {
            addCriterion("bg_light_sytle >", value, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleGreaterThanOrEqualTo(String value) {
            addCriterion("bg_light_sytle >=", value, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleLessThan(String value) {
            addCriterion("bg_light_sytle <", value, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleLessThanOrEqualTo(String value) {
            addCriterion("bg_light_sytle <=", value, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleLike(String value) {
            addCriterion("bg_light_sytle like", value, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleNotLike(String value) {
            addCriterion("bg_light_sytle not like", value, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleIn(List<String> values) {
            addCriterion("bg_light_sytle in", values, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleNotIn(List<String> values) {
            addCriterion("bg_light_sytle not in", values, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleBetween(String value1, String value2) {
            addCriterion("bg_light_sytle between", value1, value2, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleNotBetween(String value1, String value2) {
            addCriterion("bg_light_sytle not between", value1, value2, "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnIsNull() {
            addCriterion("music_turn_on is null");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnIsNotNull() {
            addCriterion("music_turn_on is not null");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnEqualTo(String value) {
            addCriterion("music_turn_on =", value, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnNotEqualTo(String value) {
            addCriterion("music_turn_on <>", value, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnGreaterThan(String value) {
            addCriterion("music_turn_on >", value, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnGreaterThanOrEqualTo(String value) {
            addCriterion("music_turn_on >=", value, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnLessThan(String value) {
            addCriterion("music_turn_on <", value, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnLessThanOrEqualTo(String value) {
            addCriterion("music_turn_on <=", value, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnLike(String value) {
            addCriterion("music_turn_on like", value, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnNotLike(String value) {
            addCriterion("music_turn_on not like", value, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnIn(List<String> values) {
            addCriterion("music_turn_on in", values, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnNotIn(List<String> values) {
            addCriterion("music_turn_on not in", values, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnBetween(String value1, String value2) {
            addCriterion("music_turn_on between", value1, value2, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnNotBetween(String value1, String value2) {
            addCriterion("music_turn_on not between", value1, value2, "musicTurnOn");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andBarrageTurnOnLikeInsensitive(String value) {
            addCriterion("upper(barrage_turn_on) like", value.toUpperCase(), "barrageTurnOn");
            return (Criteria) this;
        }

        public Criteria andLoopTurnOnLikeInsensitive(String value) {
            addCriterion("upper(loop_turn_on) like", value.toUpperCase(), "loopTurnOn");
            return (Criteria) this;
        }

        public Criteria andSytleTurnOnLikeInsensitive(String value) {
            addCriterion("upper(sytle_turn_on) like", value.toUpperCase(), "sytleTurnOn");
            return (Criteria) this;
        }

        public Criteria andSheerTurnOnLikeInsensitive(String value) {
            addCriterion("upper(sheer_turn_on) like", value.toUpperCase(), "sheerTurnOn");
            return (Criteria) this;
        }

        public Criteria andRichmanTurnOnLikeInsensitive(String value) {
            addCriterion("upper(richman_turn_on) like", value.toUpperCase(), "richmanTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeTurnOnLikeInsensitive(String value) {
            addCriterion("upper(qrcode_turn_on) like", value.toUpperCase(), "qrcodeTurnOn");
            return (Criteria) this;
        }

        public Criteria andQrcodeLightSytleLikeInsensitive(String value) {
            addCriterion("upper(qrcode_light_sytle) like", value.toUpperCase(), "qrcodeLightSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageFontSytleLikeInsensitive(String value) {
            addCriterion("upper(barrage_font_sytle) like", value.toUpperCase(), "barrageFontSytle");
            return (Criteria) this;
        }

        public Criteria andHoldscreenFontSytleLikeInsensitive(String value) {
            addCriterion("upper(holdscreen_font_sytle) like", value.toUpperCase(), "holdscreenFontSytle");
            return (Criteria) this;
        }

        public Criteria andBarrageMoveSytleLikeInsensitive(String value) {
            addCriterion("upper(barrage_move_sytle) like", value.toUpperCase(), "barrageMoveSytle");
            return (Criteria) this;
        }

        public Criteria andBgLightSytleLikeInsensitive(String value) {
            addCriterion("upper(bg_light_sytle) like", value.toUpperCase(), "bgLightSytle");
            return (Criteria) this;
        }

        public Criteria andMusicTurnOnLikeInsensitive(String value) {
            addCriterion("upper(music_turn_on) like", value.toUpperCase(), "musicTurnOn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 07 18:00:33 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weibar_merchants_barrage_setting_info
     *
     * @mbggenerated Wed Mar 07 18:00:33 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}