### 测试环境
#wechat:
#  mp:
#    appId: wxa8a4e891cc2a22b9
#    secret: 1fe11e30080dbb92da794bd13b4d9c5c
#    token: weibar2017
#    aesKey:
#  pay:
#    appId: wxa105b2133d0dd8b0
#    mchKey: nxApb3xKPYrHyRxq7wai4pWUyQOQeLyU
#    mchId: 1493754672

### 正式环境
wechat:
  mp:
    appId: wxa105b2133d0dd8b0
    secret: 4c88575249eec6450bb6cb5d296520e4
    token: weibar2017
    aesKey:
  pay:
    appId: wxd62da453fe48632c
    mchKey: nxApb3xKPYrHyRxq7wai4pWUyQOQeLyU
    mchId: 1493754672
  miniapp:
    appid: wxd62da453fe48632c
    secret: f28addb4676847e1ebd54b8e67ca7509
    token:
    aesKey:
    msgDataFormat: JSON
spring:
    datasource:
        name: test
        url: jdbc:mysql://rm-wz9l3k9adb590oksvo.mysql.rds.aliyuncs.com:3306/weibar?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
        username: root
        password: Weibar2017
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path: classpath:/templates/



