package com.weibar.service.mapper;

import com.weibar.pojo.db.UserCommissionTransaction;
import com.weibar.pojo.db.UserCommissionTransactionCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCommissionTransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int countByExample(UserCommissionTransactionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int deleteByExample(UserCommissionTransactionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int insert(UserCommissionTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int insertSelective(UserCommissionTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    List<UserCommissionTransaction> selectByExample(UserCommissionTransactionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    UserCommissionTransaction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserCommissionTransaction record, @Param("example") UserCommissionTransactionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int updateByExample(@Param("record") UserCommissionTransaction record, @Param("example") UserCommissionTransactionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int updateByPrimaryKeySelective(UserCommissionTransaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_commission_transaction
     *
     * @mbggenerated Thu Nov 16 18:00:33 CST 2017
     */
    int updateByPrimaryKey(UserCommissionTransaction record);
}